
USE LAVADEIRA_DB; 
CREATE TABLE IF NOT EXISTS TB_LAVADEIRAS (
	LAVD_CODIGO INT NOT NULL AUTO_INCREMENT,
    LAVD_NOME VARCHAR(45) NOT NULL,
    LAVD_LOGIN VARCHAR(45) NOT NULL,
    LAVD_SENHA VARCHAR(45) NOT NULL,
    LAVD_ULTIMOLOGIN DATETIME NULL,
	PRIMARY KEY (LAVD_CODIGO)

)ENGINE=InnoDB;
    

CREATE TABLE IF NOT EXISTS TB_LAVADAS (
	LAV_CODIGO INT NOT NULL AUTO_INCREMENT,
    LAV_CLIENTENOME VARCHAR(45) NOT NULL,
    LAV_DATA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAV_QUANTITY INT NOT NULL,
    LAV_VALOR DECIMAL(9,2) NOT NULL,
    LAV_LAVD_CODIGO INT NOT NULL,
    PRIMARY KEY (LAV_CODIGO),
    FOREIGN KEY (LAV_LAVD_CODIGO)REFERENCES TB_LAVADEIRAS(LAVD_CODIGO)
)ENGINE=InnoDB;


INSERT INTO TB_LAVADEIRAS (LAVD_NOME, LAVD_LOGIN, LAVD_SENHA)
	VALUES ("Ivo", "ivo@ivo.com", "123");